name: 'Generate Plantuml'
description: 'Generate uml diagrams with Plantuml Server and push them to your repository.'
author: 'grassedge'
inputs:
  path:
    description: 'path to directory which generated svg is stored'
    default: '.'
  message:
    description: 'the commit message when committing generated images'
    default: 'Render PlantUML files'
  plant_uml_server_url:
    description: 'url for plant uml server'
    default: 'http://www.plantuml.com/plantuml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'image'
  color: 'gray-dark'
