name: tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install depedencies
        run: npm install
      - name: run tests
        run: "npm run test:ci"
        env:
          CI: true
      - name: report test results
        uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: Unit Tests
      - name: CodeClimate coverage report
        uses: aktions/codeclimate-test-reporter@v1
        if: ${{ env.CC_TEST_REPORTER_ID != '' }}
        with:
          codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
          command: after-build
